# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _lpsolve
else:
    import _lpsolve

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _lpsolve.delete_SwigPyIterator

    def value(self):
        return _lpsolve.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _lpsolve.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _lpsolve.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _lpsolve.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _lpsolve.SwigPyIterator_equal(self, x)

    def copy(self):
        return _lpsolve.SwigPyIterator_copy(self)

    def next(self):
        return _lpsolve.SwigPyIterator_next(self)

    def __next__(self):
        return _lpsolve.SwigPyIterator___next__(self)

    def previous(self):
        return _lpsolve.SwigPyIterator_previous(self)

    def advance(self, n):
        return _lpsolve.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _lpsolve.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _lpsolve.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _lpsolve.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _lpsolve.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _lpsolve.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _lpsolve.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _lpsolve:
_lpsolve.SwigPyIterator_swigregister(SwigPyIterator)
class DoubleMatrix(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _lpsolve.DoubleMatrix_swiginit(self, _lpsolve.new_DoubleMatrix(*args))
    __swig_destroy__ = _lpsolve.delete_DoubleMatrix

    def Init(self, Value):
        return _lpsolve.DoubleMatrix_Init(self, Value)

    def GetAt(self, Row, Col):
        return _lpsolve.DoubleMatrix_GetAt(self, Row, Col)

    def SetAt(self, Row, Col, Value):
        return _lpsolve.DoubleMatrix_SetAt(self, Row, Col, Value)

    def Resize(self, *args):
        return _lpsolve.DoubleMatrix_Resize(self, *args)

    def NoOfRows(self):
        return _lpsolve.DoubleMatrix_NoOfRows(self)

    def NoOfCols(self):
        return _lpsolve.DoubleMatrix_NoOfCols(self)

# Register DoubleMatrix in _lpsolve:
_lpsolve.DoubleMatrix_swigregister(DoubleMatrix)
class LPMatrix(DoubleMatrix):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, LignAndKrit=0, VarsAndB=0):
        _lpsolve.LPMatrix_swiginit(self, _lpsolve.new_LPMatrix(LignAndKrit, VarsAndB))
    __swig_destroy__ = _lpsolve.delete_LPMatrix

    def Resize(self, LignAndKrit, VarsAndB):
        return _lpsolve.LPMatrix_Resize(self, LignAndKrit, VarsAndB)

    def SwapRows(self, row1, row2):
        return _lpsolve.LPMatrix_SwapRows(self, row1, row2)

    def AddToRow(self, row1, row2, c):
        return _lpsolve.LPMatrix_AddToRow(self, row1, row2, c)

    def ScaleRow(self, row, c):
        return _lpsolve.LPMatrix_ScaleRow(self, row, c)

    def ReadFromFile(self, filnavn):
        return _lpsolve.LPMatrix_ReadFromFile(self, filnavn)

# Register LPMatrix in _lpsolve:
_lpsolve.LPMatrix_swigregister(LPMatrix)
class SymbolTabel(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lpsolve.SymbolTabel_swiginit(self, _lpsolve.new_SymbolTabel())

    def InsertID(self, IdName):
        return _lpsolve.SymbolTabel_InsertID(self, IdName)

    def Find(self, id, LPMidx):
        return _lpsolve.SymbolTabel_Find(self, id, LPMidx)

    def GetID(self, LPMidx):
        return _lpsolve.SymbolTabel_GetID(self, LPMidx)

    def GetNoOfVars(self):
        return _lpsolve.SymbolTabel_GetNoOfVars(self)
    __swig_destroy__ = _lpsolve.delete_SymbolTabel

# Register SymbolTabel in _lpsolve:
_lpsolve.SymbolTabel_swigregister(SymbolTabel)
BEGIN = _lpsolve.BEGIN
ID = _lpsolve.ID
NUM = _lpsolve.NUM
PLUS = _lpsolve.PLUS
MINUS = _lpsolve.MINUS
LESS = _lpsolve.LESS
GREATER = _lpsolve.GREATER
EQUAL = _lpsolve.EQUAL
SEMICOLON = _lpsolve.SEMICOLON
END = _lpsolve.END
class Token(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lpsolve.Token_swiginit(self, _lpsolve.new_Token())

    def MakeToken(self, streng):
        return _lpsolve.Token_MakeToken(self, streng)
    tType = property(_lpsolve.Token_tType_get, _lpsolve.Token_tType_set)
    theToken = property(_lpsolve.Token_theToken_get, _lpsolve.Token_theToken_set)
    strValue = property(_lpsolve.Token_strValue_get, _lpsolve.Token_strValue_set)
    numValue = property(_lpsolve.Token_numValue_get, _lpsolve.Token_numValue_set)
    __swig_destroy__ = _lpsolve.delete_Token

# Register Token in _lpsolve:
_lpsolve.Token_swigregister(Token)
class LP(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _lpsolve.LP_swiginit(self, _lpsolve.new_LP())
    __swig_destroy__ = _lpsolve.delete_LP

    def Run(self, filnavn, trace=False):
        return _lpsolve.LP_Run(self, filnavn, trace)

    def GetFejlTekst(self):
        return _lpsolve.LP_GetFejlTekst(self)

    def GetUligheder(self):
        return _lpsolve.LP_GetUligheder(self)

    def GetMatrix(self):
        return _lpsolve.LP_GetMatrix(self)

    def GetBasisLoesning(self):
        return _lpsolve.LP_GetBasisLoesning(self)

# Register LP in _lpsolve:
_lpsolve.LP_swigregister(LP)
class StandardLP(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, LPM, trace=False):
        _lpsolve.StandardLP_swiginit(self, _lpsolve.new_StandardLP(LPM, trace))
    __swig_destroy__ = _lpsolve.delete_StandardLP

    def SolveLP(self):
        return _lpsolve.StandardLP_SolveLP(self)

# Register StandardLP in _lpsolve:
_lpsolve.StandardLP_swigregister(StandardLP)
class StraffeLP(StandardLP):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, LPM, trace=False):
        _lpsolve.StraffeLP_swiginit(self, _lpsolve.new_StraffeLP(LPM, trace))

    def SolveLP(self):
        return _lpsolve.StraffeLP_SolveLP(self)
    __swig_destroy__ = _lpsolve.delete_StraffeLP

# Register StraffeLP in _lpsolve:
_lpsolve.StraffeLP_swigregister(StraffeLP)
class StringVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _lpsolve.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lpsolve.StringVector___nonzero__(self)

    def __bool__(self):
        return _lpsolve.StringVector___bool__(self)

    def __len__(self):
        return _lpsolve.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _lpsolve.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _lpsolve.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _lpsolve.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _lpsolve.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _lpsolve.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _lpsolve.StringVector___setitem__(self, *args)

    def pop(self):
        return _lpsolve.StringVector_pop(self)

    def append(self, x):
        return _lpsolve.StringVector_append(self, x)

    def empty(self):
        return _lpsolve.StringVector_empty(self)

    def size(self):
        return _lpsolve.StringVector_size(self)

    def swap(self, v):
        return _lpsolve.StringVector_swap(self, v)

    def begin(self):
        return _lpsolve.StringVector_begin(self)

    def end(self):
        return _lpsolve.StringVector_end(self)

    def rbegin(self):
        return _lpsolve.StringVector_rbegin(self)

    def rend(self):
        return _lpsolve.StringVector_rend(self)

    def clear(self):
        return _lpsolve.StringVector_clear(self)

    def get_allocator(self):
        return _lpsolve.StringVector_get_allocator(self)

    def pop_back(self):
        return _lpsolve.StringVector_pop_back(self)

    def erase(self, *args):
        return _lpsolve.StringVector_erase(self, *args)

    def __init__(self, *args):
        _lpsolve.StringVector_swiginit(self, _lpsolve.new_StringVector(*args))

    def push_back(self, x):
        return _lpsolve.StringVector_push_back(self, x)

    def front(self):
        return _lpsolve.StringVector_front(self)

    def back(self):
        return _lpsolve.StringVector_back(self)

    def assign(self, n, x):
        return _lpsolve.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _lpsolve.StringVector_resize(self, *args)

    def insert(self, *args):
        return _lpsolve.StringVector_insert(self, *args)

    def reserve(self, n):
        return _lpsolve.StringVector_reserve(self, n)

    def capacity(self):
        return _lpsolve.StringVector_capacity(self)
    __swig_destroy__ = _lpsolve.delete_StringVector

# Register StringVector in _lpsolve:
_lpsolve.StringVector_swigregister(StringVector)
class DoublePair(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _lpsolve.DoublePair_swiginit(self, _lpsolve.new_DoublePair(*args))
    first = property(_lpsolve.DoublePair_first_get, _lpsolve.DoublePair_first_set)
    second = property(_lpsolve.DoublePair_second_get, _lpsolve.DoublePair_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _lpsolve.delete_DoublePair

# Register DoublePair in _lpsolve:
_lpsolve.DoublePair_swigregister(DoublePair)
class SolutionVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _lpsolve.SolutionVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _lpsolve.SolutionVector___nonzero__(self)

    def __bool__(self):
        return _lpsolve.SolutionVector___bool__(self)

    def __len__(self):
        return _lpsolve.SolutionVector___len__(self)

    def __getslice__(self, i, j):
        return _lpsolve.SolutionVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _lpsolve.SolutionVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _lpsolve.SolutionVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _lpsolve.SolutionVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _lpsolve.SolutionVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _lpsolve.SolutionVector___setitem__(self, *args)

    def pop(self):
        return _lpsolve.SolutionVector_pop(self)

    def append(self, x):
        return _lpsolve.SolutionVector_append(self, x)

    def empty(self):
        return _lpsolve.SolutionVector_empty(self)

    def size(self):
        return _lpsolve.SolutionVector_size(self)

    def swap(self, v):
        return _lpsolve.SolutionVector_swap(self, v)

    def begin(self):
        return _lpsolve.SolutionVector_begin(self)

    def end(self):
        return _lpsolve.SolutionVector_end(self)

    def rbegin(self):
        return _lpsolve.SolutionVector_rbegin(self)

    def rend(self):
        return _lpsolve.SolutionVector_rend(self)

    def clear(self):
        return _lpsolve.SolutionVector_clear(self)

    def get_allocator(self):
        return _lpsolve.SolutionVector_get_allocator(self)

    def pop_back(self):
        return _lpsolve.SolutionVector_pop_back(self)

    def erase(self, *args):
        return _lpsolve.SolutionVector_erase(self, *args)

    def __init__(self, *args):
        _lpsolve.SolutionVector_swiginit(self, _lpsolve.new_SolutionVector(*args))

    def push_back(self, x):
        return _lpsolve.SolutionVector_push_back(self, x)

    def front(self):
        return _lpsolve.SolutionVector_front(self)

    def back(self):
        return _lpsolve.SolutionVector_back(self)

    def assign(self, n, x):
        return _lpsolve.SolutionVector_assign(self, n, x)

    def resize(self, *args):
        return _lpsolve.SolutionVector_resize(self, *args)

    def insert(self, *args):
        return _lpsolve.SolutionVector_insert(self, *args)

    def reserve(self, n):
        return _lpsolve.SolutionVector_reserve(self, n)

    def capacity(self):
        return _lpsolve.SolutionVector_capacity(self)
    __swig_destroy__ = _lpsolve.delete_SolutionVector

# Register SolutionVector in _lpsolve:
_lpsolve.SolutionVector_swigregister(SolutionVector)

